#!/usr/bin/env bash
# Start the official vanilla Minecraft Java server after syncing to Mojang's latest release.
set -euo pipefail

DATA_DIR="${DATA_DIR:-/data}"
EULA="${EULA:-FALSE}"
VERSION="${VERSION:-LATEST}"
MEMORY="${MEMORY:-4G}"
INIT_MEMORY="${INIT_MEMORY:-$MEMORY}"
PUID="${PUID:-99}"
PGID="${PGID:-100}"
FETCH_ONLY="${FETCH_ONLY:-false}"
JVM_OPTS="${JVM_OPTS:-}"
LEVEL_NAME="${LEVEL_NAME:-world}"

cd /

reexec_as_player() {
  if [[ "$(id -u)" != "0" ]]; then
    return 0
  fi
  mkdir -p "$DATA_DIR"
  chown -R "${PUID}:${PGID}" "$DATA_DIR"
  echo "Dropping root (uid=${PUID} gid=${PGID})"
  exec setpriv --reuid="$PUID" --regid="$PGID" --clear-groups -- "$0" "$@"
}

accept_eula() {
  local v
  v="$(echo "$EULA" | tr '[:upper:]' '[:lower:]')"
  if [[ "$v" != "true" ]]; then
    echo "You must accept the Minecraft EULA to run this server:" >&2
    echo "  https://aka.ms/MinecraftEULA" >&2
    echo "Set EULA=TRUE on the container." >&2
    exit 1
  fi
  mkdir -p "$DATA_DIR"
  printf 'eula=true\n' > "${DATA_DIR}/eula.txt"
}

set_prop() {
  local key="$1" val="$2" file="${DATA_DIR}/server.properties"
  local escaped
  escaped="$(printf '%s' "$val" | sed 's/[&|\\]/\\&/g')"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${escaped}|" "$file"
  else
    printf '%s=%s\n' "$key" "$val" >> "$file"
  fi
}

set_from_env() {
  local env_name="$1" prop="$2"
  local val="${!env_name:-}"
  if [[ -n "$val" ]]; then
    set_prop "$prop" "$val"
  fi
}

write_default_properties() {
  local file="${DATA_DIR}/server.properties"
  if [[ -f "$file" ]]; then
    return 0
  fi
  cat > "$file" <<'EOF'
# generated by ghcr.io/genopimp/minecraft-server
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=Vanilla (always latest)
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=normal
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=10
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=8
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
EOF
}

apply_properties() {
  write_default_properties
  set_from_env MOTD motd
  set_from_env DIFFICULTY difficulty
  set_from_env GAMEMODE gamemode
  set_from_env MAX_PLAYERS max-players
  set_from_env ONLINE_MODE online-mode
  set_from_env LEVEL_NAME level-name
  set_from_env LEVEL_SEED level-seed
  set_from_env LEVEL_TYPE level-type
  set_from_env VIEW_DISTANCE view-distance
  set_from_env SIMULATION_DISTANCE simulation-distance
  set_from_env PVP pvp
  set_from_env HARDCORE hardcore
  set_from_env WHITE_LIST white-list
  set_from_env ENFORCE_WHITELIST enforce-whitelist
  set_from_env SPAWN_PROTECTION spawn-protection
  set_from_env ENABLE_COMMAND_BLOCK enable-command-block
  set_from_env MAX_WORLD_SIZE max-world-size
  set_from_env ENABLE_STATUS enable-status
  set_from_env ENABLE_QUERY enable-query
  set_from_env QUERY_PORT query.port
  set_from_env ENABLE_RCON enable-rcon
  set_from_env RCON_PASSWORD rcon.password
  set_from_env RCON_PORT rcon.port
  if [[ -n "${RCON_PASSWORD:-}" && -z "${ENABLE_RCON:-}" ]]; then
    set_prop enable-rcon true
  fi
}

write_name_list() {
  local dest="$1" csv="${2:-}"
  if [[ -z "$csv" ]]; then
    return 0
  fi
  mkdir -p "$DATA_DIR"
  : > "$dest"
  local IFS=','
  local name
  for name in $csv; do
    name="$(echo "$name" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if [[ -n "$name" ]]; then
      printf '%s\n' "$name" >> "$dest"
    fi
  done
}

build_java_opts() {
  local major
  major="$(detect_java_major || echo 25)"
  JAVA_ARGS=(
    "-Xms${INIT_MEMORY}"
    "-Xmx${MEMORY}"
    "-XX:+AlwaysPreTouch"
    "-XX:+UseStringDeduplication"
    "-XX:+UseZGC"
  )
  if (( major >= 24 )); then
    JAVA_ARGS+=("-XX:+UseCompactObjectHeaders")
  fi
  if [[ -n "$JVM_OPTS" ]]; then
    # shellcheck disable=SC2206
    JAVA_ARGS+=($JVM_OPTS)
  fi
}

detect_java_major() {
  java -version 2>&1 | sed -n 's/.*version "\([0-9][0-9]*\).*/\1/p' | head -1
}

MC_PID=""

stop_server() {
  echo "Caught signal; stopping Minecraft..."
  if [[ -n "${MC_PID}" ]] && kill -0 "$MC_PID" 2>/dev/null; then
    echo stop >&3 || true
    local i
    for i in $(seq 1 50); do
      kill -0 "$MC_PID" 2>/dev/null || break
      sleep 1
    done
    if kill -0 "$MC_PID" 2>/dev/null; then
      echo "Server still running; sending SIGTERM"
      kill -TERM "$MC_PID" 2>/dev/null || true
      sleep 5
    fi
    if kill -0 "$MC_PID" 2>/dev/null; then
      kill -KILL "$MC_PID" 2>/dev/null || true
    fi
    wait "$MC_PID" 2>/dev/null || true
  fi
  exec 3>&- 2>/dev/null || true
}

start_server() {
  local version jar console
  version="$(cat "${DATA_DIR}/.current-version")"
  jar="${DATA_DIR}/versions/${version}/server.jar"
  if [[ ! -f "$jar" ]]; then
    echo "ERROR: server jar missing at ${jar}" >&2
    exit 1
  fi

  build_java_opts
  console="${DATA_DIR}/.console"
  rm -f "$console"
  mkfifo "$console"

  echo "Starting vanilla ${version}  Xms=${INIT_MEMORY} Xmx=${MEMORY}"
  cd "$DATA_DIR"
  java "${JAVA_ARGS[@]}" -jar "$jar" nogui <>"$console" &
  MC_PID=$!
  exec 3>"$console"
  trap stop_server SIGTERM SIGINT
  wait "$MC_PID"
  local rc=$?
  exec 3>&- 2>/dev/null || true
  rm -f "$console"
  echo "Minecraft exited (${rc})"
  return "$rc"
}

reexec_as_player "$@"
accept_eula
export DATA_DIR VERSION LEVEL_NAME BACKUP_ON_UPGRADE KEEP_BACKUPS
/usr/local/bin/fetch-vanilla.sh

if [[ "$(echo "$FETCH_ONLY" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
  echo "FETCH_ONLY=true; not starting the server"
  exit 0
fi

apply_properties
write_name_list "${DATA_DIR}/ops.txt" "${OPS:-}"
write_name_list "${DATA_DIR}/whitelist.txt" "${WHITELIST:-}"
if [[ -n "${WHITELIST:-}" && -z "${WHITE_LIST:-}" ]]; then
  set_prop white-list true
fi

start_server
